site_name: Partner Catalog API Docs
site_url: https://rayajose.github.io/partner-catalog-api/

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: blue

repo_url: https://github.com/rayajose/partner-catalog-api

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting_started.md
  - Architecture: architecture.md
  - Deployment: deployment.md
  - API Overview: resources.md
  - Feeds API: feeds.md
  - Products API: products.md
  - Jobs API: jobs.md
  - Errors: errors.md
  - Workflows: workflows.md
  - Screenshots: screenshots.md
